const mageSkills = [
  {
    index: 0,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 1,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 2,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 3,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 4,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 5,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 6,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 7,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  {
    index: 8,
    name: "name",
    description:"description",
    requiredLvl:"reqLvl",
    icon:"icon.jpg",
    shards: [],
  },
  
]

export default mageSkills
